---
branches:
  - 2.0.0
projects:
  MultiWorld:
    path: ''
    icon: icon.png
    libs:
      Commando:
        src: CortexPE/Commando/Commando
      libpmform:
        src: CzechPMDevs/libpmform/libpmform
        version: ^1.1.0
      VanillaGenerator:
        src: CzechPMDevs/VanillaGenerator/VanillaGenerator
        version: ^0.0.5
    lint:
      phpstan: false
...
